project_id = "xgyalkuyuontavstyokg"

[functions.qpay-create-invoice]
verify_jwt = false

[functions.qpay-check-payment]
verify_jwt = false

[functions.qpay-callback]
verify_jwt = false

[functions.omniway-wallet-topup]
verify_jwt = false

[functions.omniway-wallet-check]
verify_jwt = false

[functions.storepay]
verify_jwt = false

[functions.external-api]
verify_jwt = false
